ktor:
  deployment:
    port: 8080
  application:
    modules:
      - "com.crowdproj.marketplace.app.ApplicationJvmKt.moduleJvm"
  urls:
    - "http://127.0.0.1:8080/"
    - "http://0.0.0.0:8080/"
    - "http://192.168.0.182:8080/"
  watch:
    - classes
    - resources
marketplace:
  repository:
    test: "$DB_TYPE_TEST:inmemory"
    prod: "$DB_TYPE_PROD:gremlin"
    gremlin:
      host: "$DB_GREMLIN_HOST:localhost"
      user: "$DB_GREMLIN_HOST:root"
      password: "$DB_GREMLIN_HOST:root_root"
      port: "$DB_GREMLIN_PORT:8182"
      enableSsl: false

jwt:
  issuer: "http://localhost:8081/auth/realms/crowdproj"
  audience: "product-properties"
  realm: "crowdproj-marketplace"
  clientId: "product-properties-service"
  certUrl: "http://localhost:8081/auth/realms/crowdproj/protocol/openid-connect/certs"