ktor:
  deployment:
    port: 8080
  application:
    modules:
      - "com.crowdproj.marketplace.app.ApplicationJvmKt.moduleJvm"
  urls:
    - "http://127.0.0.1:8080/"
    - "http://0.0.0.0:8080/"
    - "http://192.168.0.182:8080/"