version: "3.3"
services:
  app:
    image: product-properties-app-ktor:0.0.1
    ports:
      - "8080:8080"

  keycloak:
    image: jboss/keycloak
    ports:
      - "8081:8080"
      - "8082:9990"
    volumes:
      - ./keycloak:/tmp
    environment:
      KEYCLOAK_USER: crowdproj
      KEYCLOAK_PASSWORD: crowdproj
      KEYCLOAK_IMPORT: "/tmp/realm-export.json"
